CREATE TABLE FootballTeams
(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  Name NVARCHAR(100) NOT NULL,
  FoundedYear INT,
  Stadium NVARCHAR(150),
  City NVARCHAR(100),
  Country NVARCHAR(100),
  Manager NVARCHAR(100),
  ChampionshipsWon INT DEFAULT 0,
  IsActive BIT DEFAULT 1
);

CREATE TABLE Players
(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  Name NVARCHAR(100) NOT NULL,
  TeamId UNIQUEIDENTIFIER NOT NULL REFERENCES FootballTeams(Id),
  Position NVARCHAR(50),
  SquadNumber INT,
  Nationality NVARCHAR(100),
  IsActive BIT DEFAULT 1,
  JoinedAt DATE
);
