CREATE TABLE FootballTeams
(
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  Name NVARCHAR(100) NOT NULL,
  FoundedYear INT,
  Stadium NVARCHAR(150),
  City NVARCHAR(100),
  Country NVARCHAR(100),
  Manager NVARCHAR(100),
  ChampionshipsWon INT DEFAULT 0,
  IsActive BIT DEFAULT 1,

  CONSTRAINT PK_FootballTeams PRIMARY KEY (Id)
);

CREATE TABLE Players
(
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  Name NVARCHAR(100) NOT NULL,
  TeamId UNIQUEIDENTIFIER NOT NULL,
  Position NVARCHAR(50),
  SquadNumber INT,
  Nationality NVARCHAR(100),
  IsActive BIT DEFAULT 1,
  JoinedAt DATE,

  CONSTRAINT PK_Players PRIMARY KEY (Id),
  CONSTRAINT FK_Players_FootballTeams FOREIGN KEY (TeamId)
    REFERENCES FootballTeams (Id)
);
